# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ControlMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('stream_source', models.CharField(blank=True, max_length=1023)),
                ('background', models.ImageField(upload_to='website_background/')),
                ('main_description', models.TextField()),
                ('up_coming_description', models.TextField()),
                ('viewer_scaler', models.FloatField(default=1.0)),
                ('viewer_offset', models.FloatField(default=0.0)),
                ('viewer_random_range', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_it.Channel')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=1023)),
                ('control_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_it.ControlMeta')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UpComing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_it.Channel')),
            ],
        ),
    ]
