# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-03 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0005_auto_20170602_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcoming',
            options={'ordering': ['start_time']},
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='description',
            new_name='main_description',
        ),
        migrations.RemoveField(
            model_name='controlmeta',
            name='background',
        ),
        migrations.RemoveField(
            model_name='controlmeta',
            name='main_description',
        ),
        migrations.RemoveField(
            model_name='controlmeta',
            name='stream_source',
        ),
        migrations.RemoveField(
            model_name='controlmeta',
            name='up_coming_description',
        ),
        migrations.RemoveField(
            model_name='upcoming',
            name='date',
        ),
        migrations.AddField(
            model_name='channel',
            name='up_coming_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcoming',
            name='background',
            field=models.ImageField(null=True, upload_to='website_background/'),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='performer',
            field=models.CharField(default=1, max_length=31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcoming',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='stream_source',
            field=models.CharField(blank=True, max_length=1023),
        ),
    ]
