# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-03 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0009_auto_20170603_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcoming',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='og_image',
            field=models.CharField(default='http://live.zuirens.com', max_length=1023),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='og_title',
            field=models.CharField(default='zuirens', max_length=31),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='og_url',
            field=models.CharField(default='http://live.zuirens.com', max_length=1023),
        ),
    ]
