# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0011_auto_20170605_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replay',
            name='channel',
        ),
        migrations.AddField(
            model_name='controlmeta',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stream_it.Performer'),
        ),
        migrations.AddField(
            model_name='performer',
            name='replay_source',
            field=models.CharField(blank=True, max_length=1023),
        ),
        migrations.DeleteModel(
            name='Replay',
        ),
    ]
