# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0012_auto_20170605_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='main_description',
            new_name='main_slogan',
        ),
        migrations.AddField(
            model_name='channel',
            name='main_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
