# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0013_auto_20170605_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlmeta',
            name='on_air',
            field=models.BooleanField(default=False),
        ),
    ]
