# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0018_auto_20170607_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmeta',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='website_background/'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='sponsor_background/'),
        ),
    ]
