# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0019_auto_20170607_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmeta',
            name='background',
            field=models.ImageField(blank=True, default='/static/Zuirens-bg.jpg', null=True, upload_to='website_background/'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='background',
            field=models.ImageField(blank=True, default='/static/pioneer-dj.jpg', null=True, upload_to='sponsor_background/'),
        ),
    ]
