# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0021_auto_20170607_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='background',
            field=models.ImageField(blank=True, default='/static/img/Zuirens-bg.jpg', null=True, upload_to='sponsor_background/'),
        ),
    ]
