# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0022_auto_20170607_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.TextField(),
        ),
    ]
