# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0023_auto_20170607_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmeta',
            name='og_image',
            field=models.ImageField(blank=True, default='/static/img/Zuirens-bg.jpg', null=True, upload_to='og_image/'),
        ),
    ]
