# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0024_auto_20170607_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlmeta',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='controlmeta',
            name='og_title',
            field=models.CharField(default='zuirens', max_length=100),
        ),
    ]
