# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-19 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0028_auto_20170615_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlmeta',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
