# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-19 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0029_controlmeta_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmeta',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stream_it.Channel'),
        ),
        migrations.AlterField(
            model_name='controlmeta',
            name='name',
            field=models.CharField(default='zuirens', max_length=31),
        ),
    ]
