# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-19 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0031_auto_20170619_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmeta',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stream_it.Channel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controlmeta',
            name='performer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stream_it.Performer'),
            preserve_default=False,
        ),
    ]
