# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-19 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0033_auto_20170619_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='replay_background/'),
        ),
    ]
