# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0036_auto_20170621_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replay',
            options={'ordering': ['-date']},
        ),
    ]
