# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0038_auto_20170621_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replay',
            options={'ordering': ['date']},
        ),
    ]
