# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_it', '0039_auto_20170621_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replay',
            options={'ordering': ['-date']},
        ),
    ]
